### ISSUE TITLE
Adding support for logging network (i.e. data from the network tab of inspector)

### ISSUE THREAD

**Issue by fruch** [cisco-open-source/qtwebdriver#1]
We have an application that does lots of AJAX call, we want to be able to log those request (i.e. see their responses in the logs exposed by the Webdriver), without adding more interceptors on the "wire" between the application and the server.

similar to Chromium perfLoggingPrefs:
https://sites.google.com/a/chromium.org/chromedriver/capabilities

**Comment by nataliakoval** [comment]
Added support performance logging, from which you can get events of domain "Network".  
Limitation of usage see: [PerfLog](http://cisco-open-source.github.io/qtwebdriver/html/classwebdriver_1_1_perf_log.html)
