### ISSUE TITLE
5.6 WebEngine supports

### ISSUE THREAD

**Issue by harry-yun** [cisco-open-source/qtwebdriver#15]
Thanks for your work. Our project is moving to webengine in 5.6 and I am wondering is there a plan to support webengine in this project?
Your help is highly appreciated. Thanks.

**Comment by hekra01** [comment]
Hi,

We do not plan to support webengine at this time.
That being said, google Chromedriver and dev tools are included in qwebengine.
If you're using webviews only, then you can use Chromedriver for your selenium tests. 
On the other hand, navigating hybrid native/web views will not be supported.

**Comment by harry-yun** [comment]
Thanks for the information.
Chromedriver works in qwebengine.
Thanks.

**Comment by hekra01** [comment]
detail shere: https://github.com/cisco-open-source/qtwebdriver/issues/31#issuecomment-281014617
