### ISSUE TITLE
Qtwebdriver does not start

### ISSUE THREAD

**Issue by binodpanta** [cisco-open-source/qtwebdriver#2]
I followed instructions after downloading QtWebdriver 5.8.2 for win32

in qt console, after instalilng Qt 5.5, I run the exe and I get this error, how can this be solved?

C:\Qt\5.4\msvc2012_opengl>echo off
Setting up environment for Qt usage...
Remember to call vcvarsall.bat to complete environment setup!
[SEVR]: Root './web' does not exist!
^C
C:\Qt\5.4\msvc2012_opengl>
C:\Qt\5.4\msvc2012_opengl>vcvarsall
'vcvarsall' is not recognized as an internal or external command,
operable program or batch file.

**Comment by hekra01** [comment]
From windows prompt
For Qt5.x
-qtenv2.bat vsvars
-WebDriver.exe

For Qt4.x
-qtvars.bat vsvars
-WebDriver.exe

Or you can run WebDriver directly from a Qt command prompt (Qt command prompt sets the env so no need to run the bat).

BTW WebDriver was ported only up to Qt5.2. No tests done on later Qt versions

**Comment by binodpanta** [comment]
Thanks, same thing after that. I tried running both WebDriver and WebDriver_noWebkit.exe

Also does it matter which Visual Studio version  I use? I will repeat with Qt 5.2, let's see two command prompts in Qt, for MSVC2010 and MSVC2012

C:\Qt\5.4\msvc2012_opengl>qtenv2.bat vsvarsall
Setting up environment for Qt usage...
Remember to call vcvarsall.bat to complete environment setup!

C:\Qt\5.4\msvc2012_opengl>WebDriver-win32-Qt5.2
.0-cisco-cmt-1.3.0\WebDriver-win32-Qt5.2.0-cisco-cmt-1.3.0\WebDriver_noWebkit.ex
e
Using ./ as test data folder

C:\Qt\5.4\msvc2012_opengl>echo off
Setting up environment for Qt usage...
Remember to call vcvarsall.bat to complete environment setup!
[SEVR]: Root './web' does not exist!

**Comment by binodpanta** [comment]
Also, I see this comment in Qt website does this matter for this case? Or should I be able to use open source Qt for this?

"“Open Source Versions of Qt is not officially supported for use with any version of Visual Studio. Integration with Visual Studio is available as part of the Qt Commercial Edition.”

**Comment by hekra01** [comment]
> > should I be able to use open source Qt for this
> > Yes. Guess you main issue is using Qt5.4, Please retry with Qt5.2

**Comment by binodpanta** [comment]
Great, I installed Qt 5.2 and now in the Qt console I get this after running 

C:\Qt\Qt5.2.0\5.2.0\msvc2012_64>qtenv2.bat vsvars
Setting up environment for Qt usage...

looks okay so far, but now running the exe gives me a dialog error

C:\Qt\Qt5.2.0\5.2.0\msvc2012_64>C:\Users\bpant\Downloads\WebDriver-win32-Qt5.2.0
-cisco-cmt-1.3.0\WebDriver-win32-Qt5.2.0-cisco-cmt-1.3.0\WebDriver.exe

The application was unable to start correctly 0x00007b, Click OK to close the application!

**Comment by hekra01** [comment]
Try with the Win64 exe: WebDriver-win64-Qt4.8.5-cisco-cmt-1.2.3.zip

**Comment by binodpanta** [comment]
No luck, 

With 5.2.0 64 bit executable, I get the same error,
    Downloaded this https://github.com/cisco-open-source/qtwebdriver/releases/download/WebDriver-cisco-cmt-1.2.3/WebDriver-win64-Qt5.2.0-cisco-cmt-1.2.3.zip

With 4.8.5 64 bit executable, (this is probably expected since I installed Qt 5.2)

```
C:\Qt\Qt5.2.0\5.2.0\msvc2012_64>C:\Users\bpant\Downloads\WebDriver-win64-Qt4.8.5
```

-cisco-cmt-1.2.3\WebDriver-win64-Qt4.8.5-cisco-cmt-1.2.3\WebDriver.exe
I get 
the procedure entrypoint ?minimumSizeHint@QCheckBox@@UBE?AVQSize@@XZ could not be located in the dynamic link library QtGui4.dll

I am suspecting now whether I have the right MSVC libs

**Comment by hekra01** [comment]
hm, should use msvc2010. 
D:\test> D:\Qt\5.2.1\msvc2010_opengl\bin\qtenv2.bat vsvars
D:\test> echo off
Setting up environment for Qt usage...
Remember to call vcvarsall.bat to complete environment setup!
D:\test> WebDriver.exe --verbose
Using ./ as test data folder
D:\test> echo off
Setting up environment for Qt usage...
Remember to call vcvarsall.bat to complete environment setup!
[SEVR]: Root './web' does not exist!
[INFO](Server::Start%28%29): **\* Webdriver ****
Version:    WebDriver-cisco-cmt-1.2.3
Build Time: Apr 10 2014 19:32:23

[FINE](/session/*/timeouts/async_script): >>>>>>>>>>>>> Server::Start routes: >>>>>>>>>>>

**Comment by binodpanta** [comment]
That is interesting,

Differences on my system that I can see from yours

I do not have the msvc2010 folder in my qt , only have 2012. I do have both VS2010 and VS2012 on my machine,

C:\Qt\Qt5.2.0>cd 5.2.0

C:\Qt\Qt5.2.0\5.2.0>dir
 Volume in drive C is OSDisk
 Volume Serial Number is E636-2001

 Directory of C:\Qt\Qt5.2.0\5.2.0

03/25/2015  01:41 PM    <DIR>          .
03/25/2015  01:41 PM    <DIR>          ..
03/25/2015  01:45 PM    <DIR>          msvc2012_64_opengl
               0 File(s)              0 bytes

Next up I will try uninstalling my Qt and installing Qt 5.2.1 from here

http://download.qt.io/archive/qt/5.2/5.2.1/qt-opensource-windows-x86-msvc2012_64_opengl-5.2.1.exe

let's see if I get a different behavior

I am guessing I need the opengl one.....

 qt-opensource-windows-x86-msvc2012_64_opengl-5.2.1.exe 24-Feb-2014 12:52   553M    Details
qt-opensource-windows-x86-msvc2012_64-5.2.1.exe 24-Feb-2014 12:53   556M    Details

**Comment by hekra01** [comment]
Tests are as follows
- all msvc2010 installs: OK
- msvc 2012 installs: does not run
- mingw install: does not run

The binaries were built with Microsoft Visual Studio 2010. If you add the msvc 2010 installs you should be able to run WebDriver

**Comment by ghost** [comment]
Hi,

I work with Binod and will be taking over from here.
I have 64 bit windows machine and MSVC 2010 (which seems to be the only supported version, based on the chat thread), should I be installing , qt-windows-opensource-5.2.0-msvc2010_opengl-x86-offline.exe  version? Because based on the releases for Qt looks like 32 bit download is the only option on windows machine with MSVS2010 
http://download.qt.io/archive/qt/5.2/5.2.0/
Also, if I download the 32 bit version qt-windows-opensource-5.2.0-msvc2010_opengl-x86-offline.exe, I should be using the 32 bit webdriver- WebDriver-win32-Qt5.2.0-cisco-cmt-1.3.0.zip too?

Appreciate your help!
Thanks
Tanvi

**Comment by hekra01** [comment]
> I have 64 bit windows machine and MSVC 2010 (which seems to be the only supported version.

Yes, the prebuilt binaries were created with msvc 2010. So unless you rebuild the binaries from sourcewith msvc2012, you should use msvc2010 distrib.

> if I download the 32 bit version qt-windows-opensource-5.2.0-msvc2010_opengl-x86-offline.exe, I should be using the 32 bit webdriver- WebDriver-win32-Qt5.2.0-cisco-cmt-1.3.0.zip too?

Yes, correct

Btw, regarding issue #3, WebDriver sucessfully builds and runs on Debian 7 + gcc 2.13

**Comment by ghost** [comment]
When I execute the webdriver from QT console, here's what i see.

C:\Qt\Qt5.2.1\5.2.1\msvc2010_opengl>qtenv2.bat vsvars
Setting up environment for Qt usage...
Remember to call vcvarsall.bat to complete environment setup!

C:\Qt\Qt5.2.1\5.2.1\msvc2010_opengl>c:\WebDriver-win32-Qt5.2.0-cisco-cmt-1.2.3\W
ebDriver.exe
Using ./ as test data folder

C:\Qt\Qt5.2.1\5.2.1\msvc2010_opengl>echo off
Setting up environment for Qt usage...
Remember to call vcvarsall.bat to complete environment setup!
[SEVR]: Root './web' does not exist!

I have tried to keep all the installation exactly the way you did in the example log you provided.

Am I missing something?

**Comment by hekra01** [comment]
No, everything seems OK
Launch WD with `--verbose` to confirm. You should get traces as below

``` shell
$ ./WebDriver --verbose

Using ./ as test data folder
[SEVR]: Root './web' does not exist!
[INFO]: *** Webdriver ****
Version:    WebDriver-cisco-cmt-1.3.0
Build Time: Feb 16 2015 12:08:39
[INFO]: Server::Start()
[FINE]: >>>>>>>>>>>>> Server::Start routes: >>>>>>>>>>>
[FINE]: /status
```

Then if from a browser you connect to WD at `http://<webdriver ip>:9517/status` you should get

``` shell
{"status":0,"value":{"build":{"revision":"WebDriver-cisco-cmt-1.3.0","time":"Feb 16 2015 12:08:39 PST","version":"1.3.0"},"os":{"arch":"x86_64","name":"Linux","version":"3.16.0-23-generic"}}}
```

Then WD is OK, ready to receive commands

**Comment by ghost** [comment]
great! Looks like its all set.

Thanks

**Comment by ghost** [comment]
Hi,

We would like to use this webdriver with our tools for web browser start up and interaction.

For other browsers like chrome, we have been using remote debugging protocol so far. Is it possible to use that with your tool to make this interaction possible? If yes, how do we do that?

Thanks
Tanvi

**Comment by hekra01** [comment]
Yes, you can launch WD with remote web inspector
Use the command line switches `wi-server` and  `wi-port`, e.g:

```
WebDriver.exe --wi-server=true --wi-port=9888
```

Then in chrome open `http://<webdriver ip>:<remote debug port, e.g 9888>`
More details here: https://github.com/cisco-open-source/qtwebdriver/wiki/Command-Line-Switches

**Comment by ghost** [comment]
Thanks.

Also, we do not want to use QT console to start the driver, is it possible to do this from outside QT console?

If yes, what is the environment setup required to achieve it?

**Comment by hekra01** [comment]
You can do it from egular dos prompt or in a bat, provided that you set the same env vars  as qtvars.bat (qt4) or qtenv2.bat (qt5)
E.G, for Qt4

``` shell
D:\gitx\wdx>set QTDIR=d:\Qt\4.8.5
D:\gitx\wdx>set PATH=d:\Qt\4.8.5\bin;%PATH%
D:\gitx\wdx>WebDriver.exe --verbose
```

**Comment by ghost** [comment]
great, that works!

Thanks
Tanvi

**Comment by ghost** [comment]
Hi,

I know webdriver support is only till 5.2 version of QT, but since internally we are using QT 5.3 we would like to get it working with that version. 

I tried to use the driver with 5.3 and was unsuccessful. Is there a workaround for this?

Thanks
Tanvi

**Comment by hekra01** [comment]
You can try this

```
# update icu lib
$ sudo apt-get install libicu52

# update the paths in wd.gypi
$ vi wd.gypi
    'QT_INC_PATH': '/home/adminuser/Qt/5.3/gcc_64/include',
    'QT_BIN_PATH': '/home/adminuser/Qt/5.3/gcc_64/bin',
    'QT_LIB_PATH': '/home/adminuser/Qt/5.3/gcc_64/lib'

# rebuild WebDriver 
$ ./build.sh
```

**Comment by hekra01** [comment]
Hi

WD confirmed to work on both Qt 5.3 and 5.4, provided it is linked with the correct icu libs

**Comment by ghost** [comment]
Hi,

On Ubuntu, We tried to run the WebDriver built with web QT(5.3) against the one we have in MathWorks (5.3), but this is the error message it gives on the run machine, even after setting LD_LIBRARY_PATH  and QT_DIR values 

This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Aborted

Does this means it needs QT "installed" on that machine? We have QT installed there, and I also changed QT_DIR to point to the locally installed version instead of mathworks install (same version), still the same error.

Instead , if I run it against the downloaded web QT that the driver was built with, it runs all fine.

Are we missing something here?

PS: The MathWorks QT is slightly different in terms of the lib.so version etc than the web version, even though both are same QT 5.3. The libicuuc.so, licicudata.so and libicui18n all are version 54 while the web version has all these libraries of version 52. 

Thanks
Tanvi

**Comment by hekra01** [comment]
Hi

> This application failed to start because it could not find or load the Qt platform plugin "xcb".

Certainly libxcb missing from you host. 

> Instead , if I run it against the downloaded web QT that the driver was built with, it runs all fine.

Th WD you download was build with Qt5.2. Maybe your Qt.5.2 install is already correct or does not need xcb plugin... 

I rebuilt WD for QT.5.3 . You can see the deps of you binary with `ldd`

```
$ ldd out/bin/desktop/release/WebDriver | grep xcb
    libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fe0822ef000)
    libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fe0818a9000)
    libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007fe081692000)
    libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007fe08148c000)
    libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007fe081289000)
    libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007fe081086000)
    libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007fe080e7f000)
```

And you can see where xcb is looked for like this

```
$ld -l xcb --verbose 
found libXau.so.6 at //usr/lib/x86_64-linux-gnu/libXau.so.6
found libXdmcp.so.6 at //usr/lib/x86_64-linux-gnu/libXdmcp.so.6
found libc.so.6 at //lib/x86_64-linux-gnu/libc.so.6
found ld-linux-x86-64.so.2 at //lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
```

If not found I suggest you try this fix

```
$ sudo apt-get install libx11-xcb1
```

**Comment by ghost** [comment]
Thanks,

When I change the LB_LIBRARY_PATH value to point to the base QT directory  instead of lib folder, i move further in the process and see this

 /session/_/-cisco-visualizer-show-point
/session/_/touch/-cisco-pinch-zoom
 /session/*/touch/-cisco-pinch-rotate
 /-cisco-shutdown
 /shutdown
QXcbConnection: XCB error: 145 (Unknown), sequence: 162, resource id: 0, major code: 140 (Unknown), minor code: 20

Is this the similar thing? https://bugreports.qt.io/browse/QTBUG-31389

I am using MobaXterm to run this

Thanks
Tanvi

**Comment by hekra01** [comment]
WD start OK from you traces. Qt issue

> Is this the similar thing?  https://bugreports.qt.io/browse/QTBUG-31389

not sure, you dont mention getting `QXcbConnection: Failed to get the primary output of the screen`
try this https://forum.qt.io/topic/30791/qxcbconnection-xcb-error-165-unknown
