### ISSUE TITLE
"Enter" or "Return" not working on qtwebkit

### ISSUE THREAD

**Issue by Acanthostega** [cisco-open-source/qtwebdriver#21]
I'm testing a web application with qtwebdriver and I have a problem when doing an "Enter" or "Return". I'm running it through Selenium, and tests work with other webdriver (chromedriver, phantomjs, etc).

It occurs on the login page. The password is set into the input password element that have the focus at this moment, and text is correctly written into the element. But validating the input with "Enter" or "Return" do nothing. The unicode for "Enter" and "Return" is sent correctly because it is working with other webdrivers.

I tried to check where the command for sending a key is treating the request, and I found in src/webdriver/keys_command.cc the ExecutePost method. I see that the method is called when writing the password, but when sending "Enter", "Return", it seems to not be called. "Tab" is working, but ExecutePost is not called too for this key.

Moreover, I have warning when sending keys for the password saying:
`
[WARN]: No translation for key code. Code point: 103
`
for example.

Do you have an idea of why "Enter" doesn't work? Or can you help me to understand the flow of the treatment of a command in the code so that I can try to figure out what is the problem with this special key? Are the previous warning message relevant?

Thanks!

**Comment by hekra01** [comment]
Hi,

I tested with the html and test below.
This works in Qt4 and Qt5, i.e action is triggered by ENTER/RETURN in text input or click/submit in submit input.
Please share your test code if you still have the issue
- Selenium python

```
#!/usr/bin/env python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from time import sleep

driver = webdriver.Remote(
    desired_capabilities=webdriver.DesiredCapabilities.FIREFOX,
    command_executor='http://localhost:9517'
)
driver.get('http://127.0.0.1:8081/form.html')

# Select input
form = driver.find_elements_by_xpath("//input[@name='lastname']")[0]

print("ENTER in textfield")
form.send_keys(Keys.ENTER)
sleep(3)

print("RETURN in textfield")
form.send_keys(Keys.RETURN)
sleep(3)

# Select submit
form = driver.find_elements_by_xpath("//input[@name='send']")[0]
print("Submit on submit button")
form.submit()
sleep(3)

print("Click on submit button")
form.click()
sleep(3)

# Close the browser!
driver.quit()
```
- HTML

```
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript">
        function tempAlert(msg,duration)
        {
             var el = document.createElement("div");
             el.setAttribute("style","position:absolute;top:40%;left:20%;background-color:white;");
             el.innerHTML = msg;
             setTimeout(function(){
              el.parentNode.removeChild(el);
             },duration);
             document.body.appendChild(el);
        }
    </script>
</head>
<body>

<form action="javascript:tempAlert('Action', 2000)">
  First name:<br>
  <input type="text" name="firstname" value="Mickey">
  <br>
  Last name:<br>
  <input type="text" name="lastname" value="Mouse">
  <br><br>
  <input type="submit" name="send" value="Submit">
</form>
</body>
</html>
```

**Comment by Acanthostega** [comment]
Testing it with another web application, it appears that the Enter and Return are working. The problem that I'm encountering with the not working application is maybe related to qtwebkit and focus (I have some other problems with qtwebkit with this app), so I will close the issue since it is not qtwebdriver related.

Just to be sure, can you confirm me that with the keys command, the event is sent to the active (focused) element on the page, and that there is no specific things occurring due to the fact that the webdriver works also for Qt?

Thanks for your help !

**Comment by hekra01** [comment]
The senkeys will behave like this: https://www.w3.org/TR/webdriver/#element-send-keys
Webdriver will scroll the element into view if needed (element partially hidden), other than that, there is no specific processing
