### ISSUE TITLE
Can't build on Ubuntu 16.04 with Qt5.5.1

### ISSUE THREAD

**Issue by kellac** [cisco-open-source/qtwebdriver#26]
I get an error when I try to compile on Ubuntu 16.04 with Qt5.5.1
Here is my wd.gypi (my system language is german):
{
  'variables': {
    'QT5': '1',
    'WD_CONFIG_QWIDGET_BASE': '1',
    'WD_CONFIG_WEBKIT': '1',
    'WD_CONFIG_QUICK': '0',
    'WD_BUILD_MONGOOSE': '1',
    'WD_CONFIG_PLAYER': '1',
    'WD_CONFIG_ONE_KEYRELEASE': '0',
    'QT_BIN_PATH': '/home/kellac/Schreibtisch/Data/Qt5.5.1/5.5/gcc_64/bin',
    'QT_INC_PATH': '/home/kellac/Schreibtisch/Data/Qt5.5.1/5.5/gcc_64/include',
    'QT_LIB_PATH': '/home/kellac/Schreibtisch/Data/Qt5.5.1/5.5/gcc_64/lib',
  },
}
What I did:
I modified the do_if_modified.py (added the ", shell=True")
I get the message:
AR(target) Default/obj.target/libWebDriver_extension_qt_base.a
ar: Default/obj.target/WebDriver_extension_qt_base/geni/moc_q_view_runner.o: No such file or directory
WebDriver_extension_qt_base.target.mk:177: recipe for target 'Default/obj.target/libWebDriver_extension_qt_base.a' failed

My qt envroment is basically ok. I can compile my qr programs and I can start the programms.
I can also start the precompiled version of the webdriver.

**Comment by Krzysztow** [comment]
Basically, your error suggests the qmake hasn't been run before the compilation - `moc_*` files haven't been generated for files containing `QObject`s. 

I had the same issue and had to correct  the `wd.gypi` - make you have `qmake` available under `QT_BIN_PATH`. Remove the output directory and rebuild again. 

Hope that helps.
