### ISSUE TITLE
How about a headless example

### ISSUE THREAD

**Issue by fruch** [cisco-open-source/qtwebdriver#29]
Something like this guy is trying todo ?
http://www.grulic.org.ar/~mdione/glob//posts/implementing-selenium-with-python-and-qt/

Is it straight forward, and you connect it the same way ?

**Comment by fruch** [comment]
@hekra01 the shameless plug there was all about you 😉

**Comment by hekra01** [comment]
Hi @fruch,

We thought about headless webdriver and think it would be handled better either at host or Qt level.
* On a linux host it is straightforward:
```
$ sudo apt-get install xvfb
$ xvfb-run -a WebDriver --verbose
```
* Or this can be done via Docker: https://github.com/cisco-open-source/qtwebdriver/pull/30
```
# After building the Dockerfile, run the container, specifying the port mapping to use
$ docker run -ti --rm -p 9531:9517 <image> --verbose
```
* Or at Qt level, by passing to the QApplication the right QPA plugins: 
```
$ export QT_QPA_PLATFORM=offscreen
$ WebDriver --verbose
```
See spec: http://doc.qt.io/qt-5/qtest-overview.html
> -platform name 
This command line argument applies to all Qt applications, but might be especially useful in the context of auto-testing. By using the "offscreen" platform plugin (-platform offscreen) it's possible to have tests that use QWidget or QWindow run without showing anything on the screen. Currently the offscreen platform plugin is only fully supported on X11.

**Comment by hekra01** [comment]
FAQ updated: https://github.com/cisco-open-source/qtwebdriver/wiki/FAQ

**Comment by fruch** [comment]
Cool
