### ISSUE TITLE
on linux trying to start downloaded Qtwebdriver executable gives a library error

### ISSUE THREAD

**Issue by binodpanta** [cisco-open-source/qtwebdriver#3]
I installed Qt as per running the .run file 

qt-opensource-linux-x64-5.4.1.run

downloaded from https://www.qt.io/download-open-source/

then I downloaded the binary qtwebdriver for linux, this one

https://github.com/cisco-open-source/qtwebdriver/releases/download/WebDriver-cisco-cmt-1.3.0/WebDriver-linux64-Qt5.2.0-cisco-cmt-1.3.0.zip

Trying to start the qtwebdriver executable gives this error, what should be done to fix this?

root@vcdbat01glnxa64:/local/home/labuser/installs# /tmp/webdriver/WebDriver-linux64-Qt5.2.0-cisco-cmt-1.2.3/bin//WebDriver
/tmp/webdriver/WebDriver-linux64-Qt5.2.0-cisco-cmt-1.2.3/bin//WebDriver: error while loading shared libraries: libQt5Network.so.5: cannot open shared object file: No such file or directory

**Comment by binodpanta** [comment]
So I got around the libQt5Network.so issue by adding this to my ld_library_path 

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/Qt5.2.0/Tools/QtCreator/lib/qtcreator

but now I get another error

/tmp/webdriver/WebDriver-linux64-Qt5.2.0-cisco-cmt-1.2.3/bin//WebDriver: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/webdriver/WebDriver-linux64-Qt5.2.0-cisco-cmt-1.2.3/bin//WebDriver)

Does this mean I need to install a different version of glibc? What are the system requirements for running this lib?

Here is what ldd tells me

root@vcdbat01glnxa64:/local/home/labuser/installs# ldd /tmp/webdriver/WebDriver-linux64-Qt5.2.0-cisco-cmt-1.2.3/bin//WebDriver
/tmp/webdriver/WebDriver-linux64-Qt5.2.0-cisco-cmt-1.2.3/bin//WebDriver: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/webdriver/WebDriver-linux64-Qt5.2.0-cisco-cmt-1.2.3/bin//WebDriver)
        linux-vdso.so.1 =>  (0x00007fffa1bc9000)
        libQt5Network.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5Network.so.5 (0x00007fbb6ddb0000)
        libQt5Widgets.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5Widgets.so.5 (0x00007fbb6d52a000)
        libQt5Quick.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5Quick.so.5 (0x00007fbb6cf4f000)
        libQt5Qml.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5Qml.so.5 (0x00007fbb6c93a000)
        libQt5Sql.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5Sql.so.5 (0x00007fbb6c6f9000)
        libQt5Gui.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5Gui.so.5 (0x00007fbb6bf3b000)
        libQt5Xml.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5Xml.so.5 (0x00007fbb6bcfd000)
        libQt5OpenGL.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5OpenGL.so.5 (0x00007fbb6baa3000)
        libQt5PrintSupport.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5PrintSupport.so.5 (0x00007fbb6b833000)
        libQt5Core.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5Core.so.5 (0x00007fbb6b0f7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbb6aeb9000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fbb6acb1000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbb6aaad000)
        libicuuc.so.51 => /opt/Qt5.2.0/Tools/QtCreator/lib/qtcreator/libicuuc.so.51 (0x00007fbb6a726000)
        libicudata.so.51 => /opt/Qt5.2.0/Tools/QtCreator/lib/qtcreator/libicudata.so.51 (0x00007fbb68fdd000)
        libicui18n.so.51 => /opt/Qt5.2.0/Tools/QtCreator/lib/qtcreator/libicui18n.so.51 (0x00007fbb68bc4000)
        libQt5MultimediaWidgets.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5MultimediaWidgets.so.5 (0x00007fbb689a5000)
        libQt5Sensors.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5Sensors.so.5 (0x00007fbb68765000)
        libQt5Multimedia.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5Multimedia.so.5 (0x00007fbb68487000)
        libQt5Positioning.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5Positioning.so.5 (0x00007fbb68247000)
        libQt5WebKitWidgets.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5WebKitWidgets.so.5 (0x00007fbb68004000)
        libQt5WebKit.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5WebKit.so.5 (0x00007fbb65a36000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbb6572e000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbb654ac000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbb65296000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbb64f0b000)
        libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fbb64cbb000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fbb649c3000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fbb64687000)
        libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fbb64427000)
        libicui18n.so.53 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libicui18n.so.53 (0x00007fbb63fda000)
        libicuuc.so.53 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libicuuc.so.53 (0x00007fbb63c4f000)
        libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007fbb63a4d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbb6e118000)
        libpulse.so.0 => /usr/lib/x86_64-linux-gnu/libpulse.so.0 (0x00007fbb63802000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fbb635eb000)
        libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fbb633e1000)
        libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007fbb631df000)
        libxslt.so.1 => /usr/lib/x86_64-linux-gnu/libxslt.so.1 (0x00007fbb62fa1000)
        libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fbb62e3e000)
        libgstreamer-0.10.so.0 => /usr/lib/x86_64-linux-gnu/libgstreamer-0.10.so.0 (0x00007fbb62b56000)
        libgstapp-0.10.so.0 => /usr/lib/x86_64-linux-gnu/libgstapp-0.10.so.0 (0x00007fbb62949000)
        libgstbase-0.10.so.0 => /usr/lib/x86_64-linux-gnu/libgstbase-0.10.so.0 (0x00007fbb626f3000)
        libgstinterfaces-0.10.so.0 => /usr/lib/x86_64-linux-gnu/libgstinterfaces-0.10.so.0 (0x00007fbb624e1000)
        libgstpbutils-0.10.so.0 => /usr/lib/x86_64-linux-gnu/libgstpbutils-0.10.so.0 (0x00007fbb622bc000)
        libgstvideo-0.10.so.0 => /usr/lib/x86_64-linux-gnu/libgstvideo-0.10.so.0 (0x00007fbb6209e000)
        libQt5WebChannel.so.5 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libQt5WebChannel.so.5 (0x00007fbb61e81000)
        libffi.so.5 => /usr/lib/x86_64-linux-gnu/libffi.so.5 (0x00007fbb61c73000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fbb61a36000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fbb61816000)
        libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007fbb615f0000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fbb613de000)
        libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fbb611dc000)
        libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fbb60fd5000)
        libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fbb60dd4000)
        libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007fbb60bbc000)
        libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fbb609b5000)
        libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007fbb607a9000)
        libicudata.so.53 => /local/home/labuser/installs/qt/5.4/gcc_64/lib/libicudata.so.53 (0x00007fbb5f120000)
        libjson.so.0 => /lib/x86_64-linux-gnu/libjson.so.0 (0x00007fbb5ef16000)
        libpulsecommon-2.0.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-2.0.so (0x00007fbb5ecb2000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fbb5ea6c000)
        libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007fbb5e868000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fbb5e644000)
        libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fbb5e440000)
        liborc-0.4.so.0 => /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0 (0x00007fbb5e1c2000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fbb5dfbf000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fbb5ddba000)
        libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007fbb5db9e000)
        libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007fbb5d997000)
        libXtst.so.6 => /usr/lib/x86_64-linux-gnu/libXtst.so.6 (0x00007fbb5d791000)
        libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (0x00007fbb5d586000)
        libsndfile.so.1 => /usr/lib/x86_64-linux-gnu/libsndfile.so.1 (0x00007fbb5d31f000)
        libasyncns.so.0 => /usr/lib/x86_64-linux-gnu/libasyncns.so.0 (0x00007fbb5d119000)
        libattr.so.1 => /lib/x86_64-linux-gnu/libattr.so.1 (0x00007fbb5cf14000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fbb5cd0e000)
        libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007fbb5caff000)
        libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007fbb5c8e7000)
        libFLAC.so.8 => /usr/lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007fbb5c69a000)
        libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007fbb5c1cb000)
        libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007fbb5bf9e000)
        libogg.so.0 => /usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007fbb5bd97000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fbb5bb81000)

**Comment by hekra01** [comment]
Test works on Ubuntu 14-64 bits

``` shell
# install Qt5.2.0 or 5.2.1
$ ./qt-opensource-linux-x64-1.6.0-8-online.run 
$ wget https://github.com/cisco-open-source/qtwebdriver/releases/download/WebDriver-cisco-cmt-1.3.0/WebDriver-linux64-Qt5.2.0-cisco-cmt-1.3.0.zip
$ unzip WebDriver-linux64-Qt5.2.0-cisco-cmt-1.3.0.zip 
$ cd WebDriver-linux64-Qt5.2.0-cisco-cmt-1.3.0/bin/
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/hekra/Qt/5.2.0/gcc_64/lib
$ ./WebDriver --verbose

Using ./ as test data folder
[SEVR]: Root './web' does not exist!
[INFO]: *** Webdriver ****
Version:    WebDriver-cisco-cmt-1.3.0
Build Time: Feb 16 2015 12:08:39
[INFO]: Server::Start()
[FINE]: >>>>>>>>>>>>> Server::Start routes: >>>>>>>>>>>
[FINE]: /status
```

**Comment by binodpanta** [comment]
Thanks I will try this on a ubuntu host

However, we use Debian 7 for our dev and automation machines. Have you tried this on Debian 7? Is it expected to work there? My issue was reported on Debian 7.

I do have VMs available for Ubuntu so I can try it for now but eventual usage of qtwebdriver will be on Debian 7.

**Comment by binodpanta** [comment]
Yup on Ubuntu your steps worked for me! I am now trying to figure out how to actually run a Webdriver based test against this, will try and that and let you know

http://webserver:9517/status returns this

{"status":0,"value":{"build":{"revision":"WebDriver-cisco-cmt-1.3.0","time":"Feb 16 2015 12:08:39 PST","version":"1.3.0"},"os":{"arch":"x86_64","name":"Linux","version":"3.16.0-23-generic"}}}

**Comment by hekra01** [comment]
Same steps work on Debian 7 as well. 
Check libc version >=2.14.

``` shell
$ adminuser@debian-amd64-700:~$ ldd --version
ldd (Debian GLIBC 2.19-17) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
$ export LD_LIBRARY_PATH=/home/adminuser/Qt/5.2.0/gcc_64/lib
$ cd tmp/WebDriver-linux64-Qt5.2.0-cisco-cmt-1.3.0/bin/
$ ./WebDriver --verbose
```

**Comment by binodpanta** [comment]
Confirming that Ubunutu works great for me. I can point my RemoteWebDriver Java tests to this and have it launch/stop Qt. Thanks for this project! We need this with high priority for automating Qt based UIs, so we are willing to even invest in the project if that works out, and if that helps push it forward.

My issue is that I cannot use Debian with glibc higher than 2.13, since my administrators won't allow that until this product release is out. We are not at Debian 8 yet.

However, if I can build this locally on Debian 7 with glibc 2.13, I will be moving. Is that a possibility? Or is it not even worth trying? My first trial with it went horribly, with this being the latest status

root@vcdbat01glnxa64:/local/home/labuser/installs/qtwebdriver# cat wd.gypi
{
'variables': {
    'QT5': '1', # change to '0' to disable Qt5
    'WD_CONFIG_QWIDGET_BASE': '1', # 1 to support widget or hybrid web
    'WD_CONFIG_WEBKIT': '1', #1 to support Web views
    'WD_CONFIG_QUICK': '1', #1 to support QML
    'WD_BUILD_MONGOOSE': '1', #1 to inline mongoose code in WebDriver libraries. Otherwise CISCO_MONGOOSE paths below will be needed
    'WD_CONFIG_PLAYER': '0', #Set to 1 if qtmultimedia should be built. In case of Hawaii Cisco profile, set to 0
    'QT_INC_PATH': '<!(/bin/echo -n $QT_DIR/include)',
    'QT_BIN_PATH': '<!(/bin/echo -n $QT_DIR/bin)',
    'QT_LIB_PATH': '<!(/bin/echo -n $QT_DIR/lib)'
 },
}

root@vcdbat01glnxa64:/local/home/labuser/installs/qtwebdriver# ./build.sh  ./out
  CXX(target) Default/obj.target/WebDriver_core/src/webdriver/webdriver_version.o
  AR(target) Default/obj.target/libWebDriver_core.a
  COPY Default/libWebDriver_core.a
  RULE wd_ext_qt_gyp_WebDriver_extension_qt_base_target_generate_moc_0 inc/extension_qt/moc_q_view_runner.cc
Traceback (most recent call last):
  File "do_if_modified.py", line 25, in <module>
    p = sp.Popen([action_process, input_file , "-o", output_file], stdin=sp.PIPE, stdout=sp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 679, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make: **\* [inc/extension_qt/moc_q_view_runner.cc] Error 1
root@vcdbat01glnxa64:/local/home/labuser/installs/qtwebdriver#

**Comment by hekra01** [comment]
hm, path expansion issue in wd.gypi. Specify them explicitely

``` shell
'variables': {
    'QT5': '1', # change to '0' to disable Qt5
    'WD_CONFIG_QWIDGET_BASE': '1', # 1 to support widget or hybrid web
    'WD_CONFIG_WEBKIT': '1', #1 to support Web views
    'WD_CONFIG_QUICK': '1', #1 to support QML
    'WD_BUILD_MONGOOSE': '1', #1 to inline mongoose code in WebDriver libraries. Otherwise CISCO_MONGOOSE paths below will be needed
    'WD_CONFIG_PLAYER': '0', #Set to 1 if qtmultimedia should be built. In case of Hawaii Cisco profile, set to 0
    'QT_INC_PATH': '/home/adminuser/Qt/5.2.0/gcc_64/include',
    'QT_BIN_PATH': '/home/adminuser/Qt/5.2.0/gcc_64/bin',
    'QT_LIB_PATH': '/home/adminuser/Qt/5.2.0/gcc_64/lib'
 },
}
```

Then it works

**Comment by binodpanta** [comment]
Thanks, that works, avoiding the path expansion does it!

However, I now get these after a few minutes, I assume I have install the right version of these libraries, will give this a try 

/usr/bin/ld: cannot find -licuuc
/usr/bin/ld: cannot find -licudata
/usr/bin/ld: cannot find -licui18n
collect2: error: ld returned 1 exit status
make: **\* [Default/WebDriver] Error 1
root@vcdbat01glnxa64:/local/home/labuser/installs/qtwebdriver#

**Comment by hekra01** [comment]
Just print the search paths (in below example finding the lib succeds)

``` shell
$ ld -l icuuc --verbose
==================================================
attempt to open /usr/x86_64-linux-gnu/lib64/libicuuc.so failed
attempt to open /usr/x86_64-linux-gnu/lib64/libicuuc.a failed
attempt to open /usr/local/lib/x86_64-linux-gnu/libicuuc.so failed
attempt to open /usr/local/lib/x86_64-linux-gnu/libicuuc.a failed
attempt to open /usr/local/lib64/libicuuc.so failed
attempt to open /usr/local/lib64/libicuuc.a failed
attempt to open /lib/x86_64-linux-gnu/libicuuc.so failed
attempt to open /lib/x86_64-linux-gnu/libicuuc.a failed
attempt to open /lib64/libicuuc.so failed
attempt to open /lib64/libicuuc.a failed
attempt to open /usr/lib/x86_64-linux-gnu/libicuuc.so failed
attempt to open /usr/lib/x86_64-linux-gnu/libicuuc.a failed
attempt to open /usr/lib64/libicuuc.so failed
attempt to open /usr/lib64/libicuuc.a failed
attempt to open /usr/local/lib/libicuuc.so failed
attempt to open /usr/local/lib/libicuuc.a failed
attempt to open /lib/libicuuc.so failed
attempt to open /lib/libicuuc.a failed
attempt to open /usr/lib/libicuuc.so succeeded
-licuuc (/usr/lib/libicuuc.so)
```

But if lib not found in search path then just add a symlink, for example

``` shell
$ ln - s /home/adminuser/Qt/5.2.0/gcc_64/lib/libicuuc.so.51 /usr/lib/libicuuc.so
```

Then do the same for icudata and icui18n

**Comment by hekra01** [comment]
Hi Binod,

On our side, no issue observed running WD on Debian 7 glibc-2.13. 
Do you still have issues?

**Comment by binodpanta** [comment]
Sending security agreement for home, as discussed,


Thanks

On Mon, Apr 6, 2015 at 3:24 PM, hekra01 <notifications@github.com> wrote:

> Hi Binod,
>
> On our side, no issue observed running WD on Debian 7 glibc-2.13.
> Do you still have issues?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cisco-open-source/qtwebdriver/issues/3#issuecomment-90205058>
> .
>



-- 
-Binod

**Comment by binodpanta** [comment]
Yup I confirmed that after using tho see symlinks I can get it to work. So this means I need to arrange for these libs to be available and hopefully that's it! I can now build WebDriver on Debian 7 and run it, thanks!
