### ISSUE TITLE
Hot find own Widget in namespace with xpath 

### ISSUE THREAD

**Issue by xlazom00** [cisco-open-source/qtwebdriver#52]
I have QWidget base object with namespace 
so qtwebdriver preset object as
<TE::SegmentTableView elementId="746d4cccbaa4c597e01eb1610b30847a" className="TE::SegmentTableView">

I don't have problem with elements with namespace prefix
but everything with namespace prefix is problem.
Is this bug?

//SegmentTableView nothing
//TE::SegmentTableView  nothing
//TE\\:\\:SegmentTableView  nothing

**Comment by rdoreopto** [comment]
I also have this issue. The workaround I found was doing:

`//*[@className='TE::SegmentTableView']`

or, if the namespace is long, you could do:

`//*[contains(@className, 'SegmentTableView')]`

I'm no expert, but reading the code ([here](https://github.com/cisco-open-source/qtwebdriver/blob/145a9d3acf2ba8418b641ab4d340a3a7428885f2/src/webdriver/extension_qt/widget_view_util.cc#L71-L72) and [here](https://github.com/cisco-open-source/qtwebdriver/blob/145a9d3acf2ba8418b641ab4d340a3a7428885f2/src/webdriver/extension_qt/widget_view_util.cc#L141)), it seems that they use the class name of the qt meta object (which, I believe, is generated by QT). So I don't know if there is real solution to this problem, but I hope I could help a little bit! :)

-Raphaël

**Comment by xlazom00** [comment]
//*[contains(@className, 'SegmentTableView')] works find thx

**Comment by hekra01** [comment]
Yes, xpath issue, like this one: https://stackoverflow.com/questions/3141823/escape-colon-in-xpath-search
```
//*[@className='TE::SegmentTableView']
```
is right way to search for such elements
