### ISSUE TITLE
QTWebDriver with remote browser

### ISSUE THREAD

**Issue by fr0l** [cisco-open-source/qtwebdriver#7]
Is it possible to set up QTWebDriver to work with a remotely started QTWebKit application?
( i.e. QTWebDriver and Selenium tests are on computer1 and QTWebKit application is running on computer2 )

As to Google Chrome, it allows chromedriver to access it's Debugging Console remotely. So there should be chances to do similar with QTWebDriver.

Just as an example:
Chrome should be started with command arg `--remote-debugging-port=9222`
When creating ChromeDriver in Selenium test app, then ChromeOption is used to instruct chromedriver to not to launch new Chrome, but to use existing

```
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setExperimentalOption("debuggerAddress", "10.0.2.2:9222");

        DesiredCapabilities capabilities = DesiredCapabilities.chrome();
        capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);

        WebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:9515"), capabilities);
        driver.get("https://github.com/cisco-open-source/qtwebdriver");
```

There are screenshots bellow that illustrate a virtual Ubuntu guest with chromedriver running locally and accessing Chrome with remote-debug enabled on host computer

_Virtual Ubuntu with Selenium accessing remotely started Chrome_
![remote_ubuntu_with_chromedriver](https://cloud.githubusercontent.com/assets/3276590/7922427/de84c466-08b4-11e5-9d18-169b88078d6e.png)

_Chrome started with remote debugging enabled_
![remotebrowser_with_remote-debug_enabled](https://cloud.githubusercontent.com/assets/3276590/7922443/f8e8447c-08b4-11e5-8a25-ed47e78aa85a.png)

**Comment by hekra01** [comment]
> Is it possible to set up QTWebDriver to work with a remotely started QTWebKit application?

No, WD should be running in the same process as the Qt app it is supposed to drive

But in fact you dont need this if you goal is to use remote web inspector.
QtWD support launching wbe inspector: https://github.com/cisco-open-source/qtwebdriver/wiki/Command-Line-Switches
Just launch on target

```
$ webdriver --wi-server=true --wi-port=9222
```

Then on your host pc open http://webdriverurl:9222 in chrome to inspect

**Comment by hekra01** [comment]
closed by mistake. Try above, should be what you want.

**Comment by fr0l** [comment]
Thanks, @hekra01 !
WebInspector is not something I was aiming for.
The goal is to execute selenium tests with a remote QTWebKit application.

Do you thing it is possible to bundle QTWebDriver with QTWebKit application and access them remotely from tests (there is a white-list cmd switch)?
Chromedriver binary allows this way of work as well ( starting it with `--whitelisted-ips` cmd arg)

But then still the limitation would be not to start a separate QTWebkit app, but to use the one that is started already. (i.e. might be starting QTWebApp already instrumented by QTWebDriver )

**Comment by hekra01** [comment]
> The goal is to execute selenium tests with a remote QTWebKit application.
> Do you thing it is possible to bundle QTWebDriver with QTWebKit application and access them remotely from tests? 

Yes, this is exactly how we use it.
WD works like this.
**Computer1**
- Runs WD+qtwebkit application. 
- WD is started with with specific command line options (e.g if yo want to open 9222 remote debugging port on computer1). 
- WD is started in the same main as the Qtapp. 

```
int main(int argc, char **argv) {
    // etc...

    // Start WebDriver
    int startError = wd_server->Start();
    if (startError){
        std::cout << "Error while starting server, errorCode " << startError << std::endl;
        return startError;
    }

    QGraphicsWebView *web = new QGraphicsWebView;
    QWebPage *page = new QWebPage(web);
    // etc....

    return app.exec();
```
- Full Example here: https://github.com/cisco-open-source/qtwebdriver/blob/WD_1.X_dev/src/Test/main.cc
- more details: https://github.com/cisco-open-source/qtwebdriver/wiki

**Computer2**
- Executes Selenium tests.
- The Selenuim tests connect to the (remote) WD started and on **Computer1** 

``` java
    /**
     This java test runs on computer2: ip= 192.168.24.2
     The java test will connect to the WD listening on computer 1, ip=192.168.24.1
     (by default on port 9517)
    */
    WebDriver driver = new RemoteWebDriver(new URL("http://192.168.24.1:9517"), capabilities);
    //Next command will open a page on the remote (computer1) host
    driver.get("https://github.com/cisco-open-source/qtwebdriver");
```
- The test controls the remote app on **Computer1**
- Same with web inspector and port 9222

**Comment by fr0l** [comment]
Thanks, @hekra01 !   :thumbsup:

We'll discuss this opportunity!
